version: "3"
services:
  react-app:
    build:
      context: ./client
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - express-server

  express-server:
    build:
      context: ./server
      dockerfile: .dockerfile
    ports:
      - "3443:3443"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/yourdbname

  mongodb:
    image: mongo:latest